"""Seed data — Indian Government Schemes"""

SCHEMES = [
    {
        "scheme_id": "pm-kisan",
        "name": "PM-KISAN Samman Nidhi",
        "name_hindi": "पीएम-किसान सम्मान निधि",
        "description": "Direct income support of Rs 6000 per year to farmer families in three equal installments.",
        "description_hindi": "किसान परिवारों को प्रति वर्ष 6000 रुपये की प्रत्यक्ष आय सहायता।",
        "category": "farmer",
        "ministry": "Ministry of Agriculture",
        "eligibility_text": "All land-holding farmer families with cultivable land. Small and marginal farmers. Family includes husband, wife and minor children. Subject to exclusion criteria for higher income groups.",
        "eligibility": {"is_farmer": True, "gender": None, "caste_categories": None, "states": None, "area_type": "both"},
        "benefits": "Rs 6000 per year in 3 installments of Rs 2000 each, directly transferred to bank account.",
        "documents_required": ["Aadhaar Card", "Bank Account", "Land Records"],
        "how_to_apply": "Apply online at pmkisan.gov.in or visit nearest CSC center.",
        "apply_link": "https://pmkisan.gov.in",
        "state": "All India",
        "tags": ["farmer", "income_support", "agriculture"]
    },
    {
        "scheme_id": "pmay",
        "name": "Pradhan Mantri Awas Yojana",
        "name_hindi": "प्रधानमंत्री आवास योजना",
        "description": "Housing for All — provides affordable housing to urban and rural poor with subsidy on home loans.",
        "category": "housing",
        "ministry": "Ministry of Housing",
        "eligibility_text": "Economically weaker sections with annual income up to 3 lakh. LIG with income 3-6 lakh. MIG-I 6-12 lakh. MIG-II 12-18 lakh. Beneficiary family should not own a pucca house.",
        "eligibility": {"max_annual_income": 1800000, "bpl_required": False, "states": None, "area_type": "both"},
        "benefits": "Interest subsidy of 6.5% on home loans up to Rs 6 lakh for EWS/LIG. Subsidy up to Rs 2.67 lakh.",
        "documents_required": ["Aadhaar Card", "Income Certificate", "Bank Account", "Property Documents"],
        "how_to_apply": "Apply online at pmaymis.gov.in or through bank/housing finance company.",
        "apply_link": "https://pmaymis.gov.in",
        "state": "All India",
        "tags": ["housing", "subsidy", "loan"]
    },
    {
        "scheme_id": "pmjdy",
        "name": "Pradhan Mantri Jan Dhan Yojana",
        "name_hindi": "प्रधानमंत्री जन धन योजना",
        "description": "Financial inclusion program providing zero-balance bank accounts with RuPay debit card and insurance coverage.",
        "category": "social_security",
        "ministry": "Ministry of Finance",
        "eligibility_text": "Any Indian citizen above 10 years of age who does not have a bank account. No minimum balance required.",
        "eligibility": {"min_age": 10, "states": None},
        "benefits": "Zero balance bank account, RuPay Debit Card, Rs 1 lakh accident insurance, Rs 30,000 life insurance, overdraft facility up to Rs 10,000.",
        "documents_required": ["Aadhaar Card", "Voter ID or any valid ID"],
        "how_to_apply": "Visit nearest bank branch or banking correspondent.",
        "apply_link": "https://pmjdy.gov.in",
        "state": "All India",
        "tags": ["banking", "financial_inclusion", "insurance"]
    },
    {
        "scheme_id": "pmsby",
        "name": "Pradhan Mantri Suraksha Bima Yojana",
        "name_hindi": "प्रधानमंत्री सुरक्षा बीमा योजना",
        "description": "Accidental insurance scheme offering Rs 2 lakh coverage for just Rs 20 per year.",
        "category": "insurance",
        "ministry": "Ministry of Finance",
        "eligibility_text": "Indian citizens aged 18-70 years having a bank account with Aadhaar linked.",
        "eligibility": {"min_age": 18, "max_age": 70, "states": None},
        "benefits": "Rs 2 lakh for accidental death or permanent total disability. Rs 1 lakh for permanent partial disability. Premium only Rs 20/year.",
        "documents_required": ["Aadhaar Card", "Bank Account"],
        "how_to_apply": "Apply through bank where you have savings account. Auto-debit of Rs 20.",
        "apply_link": "https://jansuraksha.gov.in",
        "state": "All India",
        "tags": ["insurance", "accident"]
    },
    {
        "scheme_id": "pmjjby",
        "name": "Pradhan Mantri Jeevan Jyoti Bima Yojana",
        "name_hindi": "प्रधानमंत्री जीवन ज्योति बीमा योजना",
        "description": "Life insurance scheme with Rs 2 lakh coverage at Rs 436 per year premium.",
        "category": "insurance",
        "ministry": "Ministry of Finance",
        "eligibility_text": "Indian citizens aged 18-50 with bank account. Coverage up to age 55.",
        "eligibility": {"min_age": 18, "max_age": 50, "states": None},
        "benefits": "Rs 2 lakh life insurance coverage. Annual premium of Rs 436 auto-debited from bank account.",
        "documents_required": ["Aadhaar Card", "Bank Account"],
        "how_to_apply": "Enroll through bank. Premium auto-debited annually.",
        "apply_link": "https://jansuraksha.gov.in",
        "state": "All India",
        "tags": ["insurance", "life_insurance"]
    },
    {
        "scheme_id": "nsp-post-matric",
        "name": "Post Matric Scholarship for SC Students",
        "name_hindi": "एससी छात्रों के लिए पोस्ट मैट्रिक छात्रवृत्ति",
        "description": "Scholarship for SC students studying post-matriculation courses covering tuition fees and maintenance allowance.",
        "category": "scholarship",
        "ministry": "Ministry of Social Justice",
        "eligibility_text": "Students belonging to Scheduled Caste. Family income should not exceed Rs 2.5 lakh per annum. Must be studying post-matriculation or post-secondary course in recognized institution.",
        "eligibility": {"caste_categories": ["sc"], "is_student": True, "max_annual_income": 250000, "min_age": 15},
        "benefits": "Full tuition fees, maintenance allowance, book grant, and other allowances as per course.",
        "documents_required": ["Caste Certificate", "Income Certificate", "Marksheet", "Aadhaar Card", "Bank Account", "Institution Verification"],
        "how_to_apply": "Apply online at National Scholarship Portal (scholarships.gov.in).",
        "apply_link": "https://scholarships.gov.in",
        "state": "All India",
        "tags": ["scholarship", "sc", "student", "education"]
    },
    {
        "scheme_id": "nsp-st-scholarship",
        "name": "Post Matric Scholarship for ST Students",
        "name_hindi": "एसटी छात्रों के लिए पोस्ट मैट्रिक छात्रवृत्ति",
        "description": "Scholarship for ST students in post-matriculation courses to promote higher education.",
        "category": "scholarship",
        "ministry": "Ministry of Tribal Affairs",
        "eligibility_text": "Scheduled Tribe students. Family annual income not exceeding Rs 2.5 lakh. Studying in recognized institution.",
        "eligibility": {"caste_categories": ["st"], "is_student": True, "max_annual_income": 250000},
        "benefits": "Tuition fee, maintenance allowance, book bank facility.",
        "documents_required": ["Tribe Certificate", "Income Certificate", "Marksheet", "Aadhaar Card", "Bank Account"],
        "how_to_apply": "Apply via National Scholarship Portal.",
        "apply_link": "https://scholarships.gov.in",
        "state": "All India",
        "tags": ["scholarship", "st", "student"]
    },
    {
        "scheme_id": "obc-scholarship",
        "name": "Post Matric Scholarship for OBC Students",
        "name_hindi": "ओबीसी छात्रों के लिए पोस्ट मैट्रिक छात्रवृत्ति",
        "description": "Financial assistance to OBC students for post-matriculation studies.",
        "category": "scholarship",
        "ministry": "Ministry of Social Justice",
        "eligibility_text": "OBC students with family income not exceeding Rs 1 lakh per annum.",
        "eligibility": {"caste_categories": ["obc"], "is_student": True, "max_annual_income": 100000},
        "benefits": "Maintenance allowance and tuition fee reimbursement.",
        "documents_required": ["OBC Certificate", "Income Certificate", "Marksheet", "Aadhaar Card"],
        "how_to_apply": "Apply on National Scholarship Portal.",
        "apply_link": "https://scholarships.gov.in",
        "state": "All India",
        "tags": ["scholarship", "obc", "student"]
    },
    {
        "scheme_id": "minority-scholarship",
        "name": "Merit-cum-Means Scholarship for Minorities",
        "name_hindi": "अल्पसंख्यकों के लिए मेरिट-कम-मीन्स छात्रवृत्ति",
        "description": "Scholarship for meritorious students from minority communities pursuing professional and technical courses.",
        "category": "scholarship",
        "ministry": "Ministry of Minority Affairs",
        "eligibility_text": "Students from notified minority communities. Family annual income below Rs 2.5 lakh. Minimum 50% marks in previous exam.",
        "eligibility": {"is_student": True, "is_minority": True, "max_annual_income": 250000},
        "benefits": "Course fee up to Rs 20,000. Maintenance allowance Rs 1000/month for hostelers, Rs 500/month for day scholars.",
        "documents_required": ["Minority Community Certificate", "Income Certificate", "Marksheet", "Aadhaar Card", "Bank Account"],
        "how_to_apply": "Apply through National Scholarship Portal.",
        "apply_link": "https://scholarships.gov.in",
        "state": "All India",
        "tags": ["scholarship", "minority", "student"]
    },
    {
        "scheme_id": "ujjwala",
        "name": "Pradhan Mantri Ujjwala Yojana",
        "name_hindi": "प्रधानमंत्री उज्ज्वला योजना",
        "description": "Free LPG connections to women from BPL households to replace unclean cooking fuels.",
        "category": "women",
        "ministry": "Ministry of Petroleum",
        "eligibility_text": "Women above 18 years belonging to BPL families. Must not have existing LPG connection. Based on SECC-2011 data.",
        "eligibility": {"gender": ["female"], "min_age": 18, "bpl_required": True},
        "benefits": "Free LPG connection with deposit-free cylinder, regulator, and Rs 1600 subsidy. First refill and stove free.",
        "documents_required": ["BPL Card", "Aadhaar Card", "Bank Account", "Passport Photo"],
        "how_to_apply": "Visit nearest LPG distributor or apply online at pmuy.gov.in.",
        "apply_link": "https://pmuy.gov.in",
        "state": "All India",
        "tags": ["women", "bpl", "lpg", "cooking"]
    },
    {
        "scheme_id": "widow-pension",
        "name": "Indira Gandhi National Widow Pension",
        "name_hindi": "इंदिरा गांधी राष्ट्रीय विधवा पेंशन",
        "description": "Monthly pension for widows from BPL families aged 40-79 years.",
        "category": "pension",
        "ministry": "Ministry of Rural Development",
        "eligibility_text": "Widows aged 40-79 years belonging to BPL family as per NSAP guidelines.",
        "eligibility": {"gender": ["female"], "min_age": 40, "max_age": 79, "is_widow": True, "bpl_required": True},
        "benefits": "Monthly pension of Rs 300. States may add additional amount. After 80 years, shifted to Old Age Pension of Rs 500.",
        "documents_required": ["Death Certificate of Husband", "BPL Card", "Aadhaar Card", "Bank Account", "Age Proof"],
        "how_to_apply": "Apply through District Social Welfare Office or Panchayat.",
        "apply_link": "https://nsap.nic.in",
        "state": "All India",
        "tags": ["pension", "widow", "bpl", "women"]
    },
    {
        "scheme_id": "old-age-pension",
        "name": "Indira Gandhi National Old Age Pension",
        "name_hindi": "इंदिरा गांधी राष्ट्रीय वृद्धावस्था पेंशन",
        "description": "Monthly pension for senior citizens from BPL households.",
        "category": "pension",
        "ministry": "Ministry of Rural Development",
        "eligibility_text": "BPL citizens aged 60 years and above.",
        "eligibility": {"min_age": 60, "is_senior_citizen": True, "bpl_required": True},
        "benefits": "Rs 200/month for 60-79 years. Rs 500/month for 80+ years. States contribute additional amount.",
        "documents_required": ["Age Proof", "BPL Card", "Aadhaar Card", "Bank Account"],
        "how_to_apply": "Apply at District Social Welfare Office or Gram Panchayat.",
        "apply_link": "https://nsap.nic.in",
        "state": "All India",
        "tags": ["pension", "senior_citizen", "bpl"]
    },
    {
        "scheme_id": "mudra-loan",
        "name": "Pradhan Mantri MUDRA Yojana",
        "name_hindi": "प्रधानमंत्री मुद्रा योजना",
        "description": "Collateral-free loans up to Rs 10 lakh for micro and small enterprises.",
        "category": "startup",
        "ministry": "Ministry of Finance",
        "eligibility_text": "Any Indian citizen with a business plan for non-farm income generating activity. Non-corporate, non-farm small/micro enterprises. Three categories: Shishu (up to 50K), Kishore (50K-5L), Tarun (5L-10L).",
        "eligibility": {"min_age": 18, "states": None},
        "benefits": "Shishu: up to Rs 50,000. Kishore: Rs 50,000-5 lakh. Tarun: Rs 5-10 lakh. No collateral required.",
        "documents_required": ["Identity Proof", "Address Proof", "Business Plan", "Category Certificate (if SC/ST/OBC)"],
        "how_to_apply": "Apply at any bank, NBFC, or MFI. Also available on mudra.org.in.",
        "apply_link": "https://mudra.org.in",
        "state": "All India",
        "tags": ["startup", "loan", "business", "entrepreneur"]
    },
    {
        "scheme_id": "pmegp",
        "name": "Prime Minister Employment Generation Programme",
        "name_hindi": "प्रधानमंत्री रोजगार सृजन कार्यक्रम",
        "description": "Credit-linked subsidy scheme for setting up micro enterprises to generate employment.",
        "category": "employment",
        "ministry": "Ministry of MSME",
        "eligibility_text": "Individuals above 18 years. For manufacturing project cost above Rs 10 lakh and service above Rs 5 lakh, minimum 8th pass. SC/ST/Women/Minorities/Ex-servicemen get higher subsidy.",
        "eligibility": {"min_age": 18, "states": None},
        "benefits": "15-35% subsidy on project cost. Max project cost: Rs 50 lakh (manufacturing), Rs 20 lakh (service). Higher subsidy for SC/ST/Women in rural areas.",
        "documents_required": ["Aadhaar Card", "Education Certificate", "Project Report", "Caste Certificate (if applicable)"],
        "how_to_apply": "Apply online at kviconline.gov.in.",
        "apply_link": "https://www.kviconline.gov.in",
        "state": "All India",
        "tags": ["employment", "subsidy", "startup", "msme"]
    },
    {
        "scheme_id": "sukanya-samriddhi",
        "name": "Sukanya Samriddhi Yojana",
        "name_hindi": "सुकन्या समृद्धि योजना",
        "description": "Savings scheme for girl child with high interest rate and tax benefits.",
        "category": "women",
        "ministry": "Ministry of Finance",
        "eligibility_text": "Girl child below 10 years of age. Only 2 accounts allowed per family. Parents/guardians can open account.",
        "eligibility": {"gender": ["female"], "max_age": 10},
        "benefits": "High interest rate (currently ~8%). Tax-free under Section 80C. Partial withdrawal at 18 for education. Matures at 21.",
        "documents_required": ["Birth Certificate of Girl", "Parent/Guardian ID", "Address Proof"],
        "how_to_apply": "Open account at any post office or authorized bank.",
        "apply_link": "https://www.indiapost.gov.in",
        "state": "All India",
        "tags": ["women", "girl_child", "savings", "education"]
    },
    {
        "scheme_id": "ayushman-bharat",
        "name": "Ayushman Bharat PM-JAY",
        "name_hindi": "आयुष्मान भारत पीएम-जय",
        "description": "Health insurance of Rs 5 lakh per family per year for secondary and tertiary hospitalization.",
        "category": "health",
        "ministry": "Ministry of Health",
        "eligibility_text": "Families identified in SECC 2011 database. Covers rural deprived and urban worker families. About 55 crore beneficiaries.",
        "eligibility": {"bpl_required": True, "states": None},
        "benefits": "Rs 5 lakh health cover per family per year. Cashless treatment at empaneled hospitals. Covers 1,929 procedures.",
        "documents_required": ["Aadhaar Card", "Ration Card", "SECC Data Verification"],
        "how_to_apply": "Check eligibility at mera.pmjay.gov.in or call 14555.",
        "apply_link": "https://pmjay.gov.in",
        "state": "All India",
        "tags": ["health", "insurance", "hospital"]
    },
    {
        "scheme_id": "nrega",
        "name": "MGNREGA - Mahatma Gandhi National Rural Employment Guarantee",
        "name_hindi": "मनरेगा - महात्मा गांधी राष्ट्रीय ग्रामीण रोजगार गारंटी",
        "description": "Guarantees 100 days of wage employment per year to every rural household willing to do unskilled manual work.",
        "category": "employment",
        "ministry": "Ministry of Rural Development",
        "eligibility_text": "Adult members of rural households willing to do unskilled manual work. Must have job card.",
        "eligibility": {"min_age": 18, "area_type": "rural"},
        "benefits": "100 days guaranteed wage employment. Wages paid within 15 days. Unemployment allowance if work not provided within 15 days.",
        "documents_required": ["Job Card", "Aadhaar Card", "Bank/Post Office Account"],
        "how_to_apply": "Register at Gram Panchayat to get Job Card.",
        "apply_link": "https://nrega.nic.in",
        "state": "All India",
        "tags": ["employment", "rural", "unskilled"]
    },
    {
        "scheme_id": "pmfby",
        "name": "Pradhan Mantri Fasal Bima Yojana",
        "name_hindi": "प्रधानमंत्री फसल बीमा योजना",
        "description": "Crop insurance scheme protecting farmers against crop loss due to natural calamities.",
        "category": "farmer",
        "ministry": "Ministry of Agriculture",
        "eligibility_text": "All farmers including sharecroppers and tenant farmers growing notified crops. Both loanee and non-loanee farmers.",
        "eligibility": {"is_farmer": True, "states": None},
        "benefits": "Insurance coverage for crop loss. Premium: 2% for Kharif, 1.5% for Rabi, 5% for commercial crops. Rest paid by government.",
        "documents_required": ["Land Records", "Aadhaar Card", "Bank Account", "Sowing Certificate"],
        "how_to_apply": "Apply through bank, CSC, or pmfby.gov.in before crop season deadline.",
        "apply_link": "https://pmfby.gov.in",
        "state": "All India",
        "tags": ["farmer", "insurance", "crop"]
    },
    {
        "scheme_id": "skill-india",
        "name": "Pradhan Mantri Kaushal Vikas Yojana",
        "name_hindi": "प्रधानमंत्री कौशल विकास योजना",
        "description": "Free skill training and certification for Indian youth to improve employability.",
        "category": "skill_development",
        "ministry": "Ministry of Skill Development",
        "eligibility_text": "Indian citizens aged 15-45 years. School/college dropouts or unemployed. Aadhaar and bank account required.",
        "eligibility": {"min_age": 15, "max_age": 45},
        "benefits": "Free skill training, certification, monetary reward on completion, placement assistance.",
        "documents_required": ["Aadhaar Card", "Bank Account", "Education Certificate"],
        "how_to_apply": "Register at nearest PMKVY training center or pmkvyofficial.org.",
        "apply_link": "https://pmkvyofficial.org",
        "state": "All India",
        "tags": ["skill", "training", "employment", "youth"]
    },
    {
        "scheme_id": "disability-pension",
        "name": "Indira Gandhi National Disability Pension",
        "name_hindi": "इंदिरा गांधी राष्ट्रीय विकलांगता पेंशन",
        "description": "Monthly pension for persons with severe and multiple disabilities from BPL families.",
        "category": "pension",
        "ministry": "Ministry of Rural Development",
        "eligibility_text": "BPL persons aged 18-79 with 80% or more disability. Multiple disabilities with 40% and above also eligible.",
        "eligibility": {"min_age": 18, "max_age": 79, "is_disabled": True, "bpl_required": True},
        "benefits": "Rs 300 per month pension. States may provide additional amount.",
        "documents_required": ["Disability Certificate", "BPL Card", "Aadhaar Card", "Bank Account"],
        "how_to_apply": "Apply at District Social Welfare Office.",
        "apply_link": "https://nsap.nic.in",
        "state": "All India",
        "tags": ["pension", "disability", "bpl"]
    },
    {
        "scheme_id": "standup-india",
        "name": "Stand-Up India",
        "name_hindi": "स्टैंड-अप इंडिया",
        "description": "Bank loans between Rs 10 lakh to Rs 1 crore for SC/ST and women entrepreneurs.",
        "category": "startup",
        "ministry": "Ministry of Finance",
        "eligibility_text": "SC/ST and/or women entrepreneurs above 18 years. For greenfield (first-time) enterprise in manufacturing, services, or trading. Should not be in default to any bank.",
        "eligibility": {"min_age": 18, "gender": ["female"], "caste_categories": ["sc", "st"]},
        "benefits": "Composite loan of Rs 10 lakh to Rs 1 crore. Covers 75% of project cost. Repayment in 7 years with moratorium of 18 months.",
        "documents_required": ["Identity Proof", "Address Proof", "Business Plan", "Caste Certificate/Gender Proof", "IT Returns"],
        "how_to_apply": "Apply at standupmitra.in or visit any scheduled bank branch.",
        "apply_link": "https://standupmitra.in",
        "state": "All India",
        "tags": ["startup", "sc", "st", "women", "loan"]
    },
    {
        "scheme_id": "beti-bachao",
        "name": "Beti Bachao Beti Padhao",
        "name_hindi": "बेटी बचाओ बेटी पढ़ाओ",
        "description": "Campaign to protect and educate the girl child, with focus on improving child sex ratio.",
        "category": "women",
        "ministry": "Ministry of Women & Child Development",
        "eligibility_text": "Girl children. Parents can open Sukanya Samriddhi Account under this. Focus districts with low CSR.",
        "eligibility": {"gender": ["female"], "max_age": 10},
        "benefits": "Awareness programs, institutional support, Sukanya Samriddhi account facility, scholarship linkages.",
        "documents_required": ["Birth Certificate", "Aadhaar of Parent"],
        "how_to_apply": "Contact nearest Anganwadi or District Administration.",
        "apply_link": "https://wcd.nic.in",
        "state": "All India",
        "tags": ["women", "girl_child", "education"]
    },
    {
        "scheme_id": "maternity-benefit",
        "name": "Pradhan Mantri Matru Vandana Yojana",
        "name_hindi": "प्रधानमंत्री मातृ वंदना योजना",
        "description": "Cash benefit of Rs 5000 for pregnant and lactating mothers for first living child.",
        "category": "women",
        "ministry": "Ministry of Women & Child Development",
        "eligibility_text": "Pregnant women and lactating mothers for first child. Not applicable for government/PSU employees.",
        "eligibility": {"gender": ["female"], "min_age": 19},
        "benefits": "Rs 5,000 in 3 installments. Rs 1,000 at registration, Rs 2,000 after 6 months, Rs 2,000 after child birth registration.",
        "documents_required": ["Aadhaar Card", "Bank Account", "MCP Card", "Pregnancy Registration"],
        "how_to_apply": "Register at nearest Anganwadi Centre or approved health facility.",
        "apply_link": "https://wcd.nic.in",
        "state": "All India",
        "tags": ["women", "maternity", "health"]
    },
    {
        "scheme_id": "atal-pension",
        "name": "Atal Pension Yojana",
        "name_hindi": "अटल पेंशन योजना",
        "description": "Guaranteed pension of Rs 1000-5000/month after age 60 for unorganized sector workers.",
        "category": "pension",
        "ministry": "Ministry of Finance",
        "eligibility_text": "Indian citizens aged 18-40 years. Must have bank account with Aadhaar linked. Applicable for unorganized sector workers not covered under any statutory social security scheme.",
        "eligibility": {"min_age": 18, "max_age": 40},
        "benefits": "Guaranteed pension Rs 1000-5000 per month after 60. Government co-contributes 50% for eligible subscribers.",
        "documents_required": ["Aadhaar Card", "Bank Account", "Mobile Number"],
        "how_to_apply": "Apply at bank where you hold savings account.",
        "apply_link": "https://npscra.nsdl.co.in",
        "state": "All India",
        "tags": ["pension", "unorganized_sector"]
    },
    {
        "scheme_id": "free-ration",
        "name": "Pradhan Mantri Garib Kalyan Anna Yojana",
        "name_hindi": "प्रधानमंत्री गरीब कल्याण अन्न योजना",
        "description": "Free foodgrains to priority households and Antyodaya families through PDS.",
        "category": "social_security",
        "ministry": "Ministry of Consumer Affairs",
        "eligibility_text": "Families covered under National Food Security Act. Priority Households and Antyodaya Anna Yojana (AAY) families.",
        "eligibility": {"bpl_required": True},
        "benefits": "5 kg free foodgrains per person per month for priority households. 35 kg per family per month for AAY families.",
        "documents_required": ["Ration Card", "Aadhaar Card"],
        "how_to_apply": "Visit nearest Fair Price Shop with ration card.",
        "apply_link": "https://nfsa.gov.in",
        "state": "All India",
        "tags": ["food", "bpl", "ration"]
    }
]
